# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0ce90444a23d5ef1a74f2649365b7025f88bb5ce459adcdf153bd00a1a2a7ae95da9ed742b6248b9243e7463f11e9880d4e522dcaaa1132135b91db87c6001e

test:
  secret_key_base: 01f17ae27c8fb5e0c7273ad633d9b01868dc403947babf866e343814ccdfc15d00337f5483aa43738e3cd8065bc09539f6deda13092941b85d31a73e8020cc68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
